import cv2
import numpy as np
import matplotlib.pyplot as plt
daun = cv2.imread('download (1).jpg')
daun = cv2.cvtColor(daun, cv2.COLOR_BGR2RGB)
hsv_daun = cv2.cvtColor(daun, cv2.COLOR_RGB2HSV)
light_orange = (1, 190, 200)
dark_orange = (18, 255, 255)
mask = cv2.inRange(hsv_daun, light_orange, dark_orange)
light_white = (0, 0, 200)
dark_white = (145, 60, 255)
mask_white = cv2.inRange(hsv_daun, light_white, dark_white)
final_mask = mask + mask_white
final_result = cv2.bitwise_and(daun, daun, mask=final_mask)
plt.subplot(2, 2, 1)
plt.imshow(daun)
plt.axis('off')
plt.title("Original Image")
plt.subplot(2, 2, 2)
plt.imshow(hsv_daun)
plt.axis('off')
plt.title("HVS Image")
plt.subplot(2, 2, 3)
plt.imshow(final_mask)
plt.axis('off')
plt.title("Mask Image")
plt.subplot(2, 2, 4)
plt.imshow(final_result)
plt.axis('off')
plt.title("Hasil Image")
plt.show()