import cv2
import numpy as np
import matplotlib.pyplot as plt
daun = cv2.imread('download (1).jpg')
daun = cv2.cvtColor(daun, cv2.COLOR_BGR2RGB)
hsv_daun = cv2.cvtColor(daun, cv2.COLOR_RGB2HSV)
light_orange = (1, 190, 200)
dark_orange = (18, 255, 255)
mask = cv2.inRange(hsv_daun, light_orange, dark_orange)
result = cv2.bitwise_and(daun, daun, mask=mask)
plt.subplot(2, 2, 1)
plt.imshow(daun)
plt.axis('off')
plt.title("Original Image")
plt.subplot(2, 2, 2)
plt.imshow(hsv_daun)
plt.axis('off')
plt.title("HVS Image")
plt.subplot(2, 2, 3)
plt.imshow(mask)
plt.axis('off')
plt.title("Mask Image")
plt.subplot(2, 2, 4)
plt.imshow(result)
plt.axis('off')
plt.title("Hasil Image")
plt.show()